### ISSUE TITLE
Remove not needed (interactive) calls?

### ISSUE THREAD

**Issue by Silex** [roman/navorski.el#3]
Hello,

Can you explain why you have so much `interactive` functions? It only serves `M-x` as far as I know.

**Comment by roman** [comment]
@Silex  thank you so much for your feedback. I worked all this issues in this commits:
- f3c6a7f
- 74f6580

Let me know if things work for you now, if so, can you please close the issue?

Note the changes are on the [development](http://github.com/roman/navorski.el/tree/development) branch

**Comment by Silex** [comment]
Works for me :+1:
