### ISSUE TITLE
-navorski-merge-alist: Wrong type argument: listp, t

### ISSUE THREAD

**Issue by Silex** [roman/navorski.el#4]
Hello, this happen when running `nav/term`. Probably a silly error, will investiguate later.

**Comment by roman** [comment]
Fixed on f3c6a7f

Can you please test it and in case it is fixed close this ticket?

Note the changes are on the [development](http://github.com/roman/navorski.el/tree/development) branch

**Comment by Silex** [comment]
Yep, it's fixed.
