### ISSUE TITLE
Code not working and examples not consistent - merge problem?

### ISSUE THREAD

**Issue by duerrp** [roman/navorski.el#5]
Interesting project, but there are a few problems in the last version I got from MELPA: 
- As far as I can tell `-navorski-profile-get-buffer` should be replaced by `-navorski-get-buffer`.
- The examples in the readme need `:interactive t` to work as advertised.
- `:process-path` should be `:program-path`

**Comment by roman** [comment]
@duerrp thank you so much for your feedback. I worked all this issues in this commits:
- f3c6a7ff15fbefc9d930e786c977e9aff42bf249
- 74f65801ee49ffc494236de5c1400123ace7f349

Let me know if things work for you now, if so, can you please close the issue?

Note the changes are on the [development](http://github.com/roman/navorski.el/tree/development) branch

**Comment by duerrp** [comment]
Great, thanks.
