### ISSUE TITLE
idea: nav/tramp-to-remote-term

### ISSUE THREAD

**Issue by Silex** [roman/navorski.el#7]
Hello,

`M-x nav/setup-tramp` works smoothly but only if you started with a terminal. If you started with a tramp session, it'd be nice to type `M-x nav/tramp-to-remote-term` and find ourselves in a terminal ssh'ed at the correct host/pwd.

I shouldn't be too hard to write, I might make a PR once I find a bit of time.

**Comment by roman** [comment]
That would be great! I'll be checking out the PR section for it :-)

Thanks!

**Comment by Silex** [comment]
Closing because of #8
