### ISSUE TITLE
multi-term update (unknown function multi-term-list)

### ISSUE THREAD

**Issue by Silex** [roman/navorski.el#9]
Hello,

I pushed what think is a fix for the recent multi-term update, but I'm not sure if it's correct (see the multi-term-update branch).

Also I'm not sure how to handle the package version... because with older version of multi-term we want to depend on `multi-term-list`

Any idea?

**Comment by Silex** [comment]
Alright, based on the discussion that happend at MELPA I think I'll merge this to master, as soon as you agree that it does what's intended. I'm not sure `multi-term-buffer-list` _really_ replaces `(multi-term-list)`.

**Comment by Silex** [comment]
I went ahead and merged it to master becaue the package was MELPA-broken since too long.

**Comment by roman** [comment]
:+1:  Awesome, thanks for that
